version: '3'

services:
  orm-app:
    container_name: orm-app
    build: .
    image: orm-app
    env_file: ./.env
    ports: 
      - 5000:5000 
    restart: on-failure
    volumes:
      - ./app:/app       
    networks:
      - orm
    depends_on:
      - orm-mdb

  orm-mdb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:
      - dbdata:/data/db
    networks:
      - orm
  
  # mongo-express:
  #   image: mongo-express
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_BASICAUTH_USERNAME: ${ME_BASIC_USER}
  #     ME_CONFIG_BASICAUTH_PASSWORD: ${ME_BASIC_PASSWORD}!
  #     ME_CONFIG_MONGODB_PORT: ${MONGODB_PORT}
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_ADMIN_USER}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_ADMIN_PASSWORD}!
  #   depends_on:
  #     - orm-mdb
  #   networks:
  #     - orm

# Database volumes
volumes:
  dbdata:

# Networks to be created to facilitate communication between containers
networks:
  orm:
    driver: bridge

